<?php

require_once(__DIR__ . "/parts/header.php");
require_once(__DIR__ . "../config/config.php");
?>


<div class="flex-other">
  <div>1</div>
  <div>2</div>
</div>
<br>
<div class="flex-other">
  <div>1</div>
  <div>2</div>
</div>
<br>
<div class="flex-other">
  <div>1</div>
  <div>2</div>
</div>
<br>
<div class="flex-other">
  <div>1</div>
  <div>2</div>
</div>





<?php require_once(__DIR__ . "/parts/footer.php"); ?>